### ISSUE TITLE
Notifying Fathers via SMS regarding their child's thali

### ISSUE THREAD

**Issue by murtraja** [murtaza52/faiz-static#277]
1. Father's number not updated for every record
2. Some people have entered international numbers

**Comment by yusuf4u52** [comment]
Do we know how will we identify if the number is international or not?

**Comment by murtraja** [comment]
We might use regex for that
https://stackoverflow.com/questions/18351553/regular-expression-validation-for-indian-phone-number-and-mobile-number
https://stackoverflow.com/questions/19840301/jquery-to-validate-phone-number

if you have a better option, let me know. i am planning to do the validation client side itself (in the selection section)

**Comment by murtraja** [comment]
#286
