### ISSUE TITLE
Please remove empty categories from email

### ISSUE THREAD

**Issue by murtaza52** [murtaza52/faiz-static#62]
Below is a generated email. In it the last 4 categories are empty, please remove any categories that are empty - 

Start Thali
598 - Shabbir Ashikhussain Wadhvanwala - 9016584488 - Add lane no 5 bhagyoday nagar, nr metro raikar nivas, 3 rd floor Pune kondwa
41 - Taher Kanchwala - 9022434144 - 22, B-1, Pudumjee Paradise Society, Bhawani Peth, camp, Pune

Stop Thali
376

Start Transport

Stop Transport

Update Details

New registration

Count 
182

**Comment by yusuf4u52** [comment]
Merge pull request #151
