### ISSUE TITLE
My transporter field doesnt show transporter name

### ISSUE THREAD

**Issue by murtaza52** [murtaza52/faiz-static#76]
Transport field shows just "Transport" and doesn't show the name of the bhai for my thaali 183.

**Comment by yusuf4u52** [comment]
This is not an issue - its by design :)

**Comment by murtaza52** [comment]
Why ?

If you dont wasnt to show the transporter then dont show the field at all.
It looks funny that I see Transporter under the field.

Second they should certainly know who their transporters are, and also have
their numbers. It helps in cases of emergencies. Whats the idea behind not
showing it ?

**Comment by yusuf4u52** [comment]
The idea is when you start transport the user doesn't know whose going to
be his transporter. The transporter field is temporary and BB would assign
a transporter on Pending Actions page.
For you I assigned Azhar bhai ( check again).

**Comment by yusuf4u52** [comment]
Emergencies ????? :)

**Comment by murtaza52** [comment]
Are bhai, my transporter was assigned before and showing Azhar bhai. Then
suddenly yesterday it stopped showing, after I did start / stop.

So if its not assigned then please show "Not Assigned". All messages should
be something the end user can understand. To me as an end user it seems the
system is broken.

The system should be self explanatory, there should be no need for them to
contact us, we have to bring our messages to that level.
