### ISSUE TITLE
Replace the popup on wrong google login with the following

### ISSUE THREAD

**Issue by murtaza52** [murtaza52/faiz-static#77]
When a person tries to login, and if his email is not registered he gets the following alert -

"Ooops! Something went wrong. Send and email to help@faizstudents.com"

Replace this with -
1) Bootstrap popup.
2) Give the following msg - "The email address murtaza@abc.com is not registered with us. Either login with your registered email address or email us on help@faizstudents.com to register your email address."

**Comment by yusuf4u52** [comment]
I have told this before alert is is not just the email address not exist in database problem. Can't put this text.

**Comment by murtaza52** [comment]
Show the email address, so that the person understands y the login is
wrong.

Y cant we give better msgs ? There should be no need for the person to send
email to help. He should understand by looking at the msg that he has
logged in with an email address which is not registered.

Also replace the alerts with bootstrap popups.

**Comment by yusuf4u52** [comment]
done
