### ISSUE TITLE
Email is not picking up the correct field

### ISSUE THREAD

**Issue by murtaza52** [murtaza52/faiz-static#86]
Salam %name%,

Your thali has been not been activated as we are not currently able to deliver thali at your provided address. For any queries please mail us at help@faizstudents.com.

Regards,
Faiz Team

There is also grammatical mistake in the above text. Change it to 

Salam %name%,

Your thaali has not been activated as we are not currently able to deliver at your address. For any queries please mail us at help@faizstudents.com.

Regards,
Faiz Team

**Comment by yusuf4u52** [comment]
#87

**Comment by murtaza52** [comment]
Did we correct the text too ?

**Comment by yusuf4u52** [comment]
Yes
