### ISSUE TITLE
When sending the CR email deal with conflicting requests

### ISSUE THREAD

**Issue by murtaza52** [murtaza52/faiz-static#99]
Lets say I first stopped the thaali and then again started, in the CR email my thali will come under both start and stop. 

The email should deal with 2 cases - 

1) Start / Stop Thaali - If the same thaali appears in both then consider the latest and discrad the older entries.  

2) Start / Stop tarnsport - same as above. 

Also deal with multiple entries under the same banner. ex multiple starts for 183.

**Comment by yusuf4u52** [comment]
Duplicate entries will now not be present (Fixed)

**Comment by yusuf4u52** [comment]
Reverted the change.

**Comment by yusuf4u52** [comment]
Duplicate entries will now not be there.(Fixed)
If multiple action by one thali we need to only send the latest one. (Pending)

**Comment by yusuf4u52** [comment]
fixed in #201
